---
title: "Demographics Report"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readxl)
# remotes::install_github("samuelkaminsky/SKTools")
library(SKTools)
library(plotly)
library(psych)
library(jtools)
library(shiny)
```

```{r, include=FALSE}
Engage <- read.csv("Engagement_Pos Qual_2022-05-01_Choice Text.csv", skip = 1) %>% 
  slice(-1)

Demographics <- Engage %>% 
  select(Response.ID,Duration..in.seconds.,Finished,Location.Latitude,Location.Longitude,Emploment.Status=Which.of.the.following.categories.best.describes.your.employment.status.,
         Industry=Which.of.the.following.categories.best.describes.the.industry.you.work.in.,Size.of.Organization=What.is.the.size.of.the.organization.you.work.for.,
         Work.Arrangement=Which.of.the.following.categories.best.describes.your.current.work.arrangement.,Job.Title=What.is.your.job.title.,
         Job.Managerial.Responsibilities=What.is.the.best.description.of.your.job.s.managerial.responsibilities., Age=Please.indicate.your.age, Education=Please.indicate.your.education.level,
         Gender=To.which.gender.identity.do.you.most.identify.) %>% 
  rename(Time=Duration..in.seconds.)
```

# Report 

This dashboard will report out all demographic variables we have from our Engagement Surver (Post Qualtric) 2022-05-01.

# Employeement Status {data-navmenu="Indicators"}

```{r}
es <-Demographics %>% 
  select(Emploment.Status) %>% 
  frequencies(perc=T) %>% 
  ggplot(., aes(x = value, y = perc, fill= value)) +
  geom_bar(stat = "identity", position = position_dodge(), alpha = .7) +
  scale_fill_manual(values = c("#00c3e0", "#002046", "#F8BA4E", "#FFA28F", "#9CE8F2", "gray")) +
  theme_nice()
  

ggplotly(es)
```

# Industry {data-navmenu="Indicators"}

```{r}
i <-Demographics %>% 
  select(Industry) %>% 
  frequencies(perc=T) %>% 
  ggplot(., aes(x = value, y = perc, fill= value)) +
  geom_bar(stat = "identity", position = position_dodge(), alpha = .7) +
  theme_nice()
  

ggplotly(i)
```

# Size of Organization {data-navmenu="Indicators"}

```{r}
so <-Demographics %>% 
  select(Size.of.Organization) %>% 
  frequencies(perc=T) %>% 
  ggplot(., aes(x = value, y = perc, fill= value)) +
  geom_bar(stat = "identity", position = position_dodge(), alpha = .7) +
  theme_nice()
  

ggplotly(so)
```

# Gender {data-navmenu="Biodata"}
```{r}
gen <- Demographics %>% 
  select(Gender) %>% 
  frequencies(perc=T) %>% 
  ggplot(., aes(x = value, y = perc, fill= value)) +
  geom_bar(stat = "identity", position = position_dodge(), alpha = .7) +
  theme_nice()
  

ggplotly(gen)
```

# Age {data-navmenu="Biodata"}
```{r}
age <- Demographics %>% 
  select(Age) %>% 
  frequencies(perc=T) %>% 
  ggplot(., aes(x = value, y = perc, fill= value)) +
  geom_bar(stat = "identity", position = position_dodge(), alpha = .7) +
  theme_nice()
  

ggplotly(age)
```

# Education {data-navmenu="Biodata"}
```{r}
ed <- Demographics %>% 
  select(Education) %>% 
  frequencies(perc=T) %>% 
  ggplot(., aes(x = value, y = perc, fill= value)) +
  geom_bar(stat = "identity", position = position_dodge(), alpha = .7) +
  theme_nice()
  

ggplotly(ed)
```